config/routes.rb
Rails.application.routes.draw do

  root to: 'meetups#index'

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users, only: [:show]
  resources :maps, only: [:index]
  match '/auth', :to => 'authorizations#new', :as => :login, :via => [:get, :post]
  match '/auth/:provider/callback', :to => 'authorizations#create', :via => [:get, :post]
  match '/auth/failure', :to => 'authorizations#failure', :via => [:get, :post]

  get 'search', to: 'search#search'

  resources :meetups
  resources :meetup_memberships

  resources :questions do
    resources :responses
  end
  resources :courses
  resources :groups, only: [:index]
  resources :conversations do
    resources :messages
  end

end

app/models/question.rb
require 'elasticsearch/model'

class Question < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks	
  belongs_to :user
  belongs_to :course
  has_many :responses
  validates_presence_of :content, :title, :user_id

  self.per_page = 20
end

Question.import

app/controllers/question_controller.rb
class QuestionsController < ApplicationController
  respond_to :html, :js

def index
    @questions = Question.order(created_at: :desc).limit(10)
    @user = User.new
  end

def new
   #will render new form
  @question = Question.new
end

def create
  # @question = Question.new(question_params) 
  if submit_new_question?
      @question.user = current_user
  render 'new' unless @question.save
end

def show
  @question = Question.find(params[:id])
    if @question.save
      render 'show'
    else
      render 'new'
    end
  end

  private
  def question_params
    #get attributed from db
    params.require(:question).permit(:content, :title)
  end

  def submit_new_question?
    params[:commit] == "Submit New Question"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  respond_to :html, :js

  def index
    @question = Question.new
    @questions = Question.paginate(:page => params[:page]).order('created_at DESC')


  end

 def create
  @question = Question.new(question_params)

  if submit_new_question?
    @question.user = current_user
    @questions = Question.order(created_at: :desc).limit(10)

    render 'new' unless @question.save!

  elsif preview?
    @content = markdown(params[:question][:content]).gsub("\n","<p></p>")
    render :preview
  end
end

def show
  @question = Question.find(params[:id])
  if @question.save
    render 'show'
  else
    render 'new'
  end
end

def edit
  @question = Question.find(params[:id])
  render 'edit'
end

def update
  @question = Question.find(params[:id])
  @question.update(question_params)
end

private
def question_params
    #get attributed from db
    params.require(:question).permit(:content, :title)
  end

  def submit_new_question?
    params[:commit] == "Submit New Question"
  end

  def preview?
    params[:commit] == "Preview"
  end
end

app/views/questions/_edit_question_form.html.erb
<%=form_for @question, remote: true do |f| %>
<br>
<%= f.text_field :title, placeholder: "title" %>
<br>
<br>
<%= f.text_area :content, placeholder: "content"%>
<br>
<br>
<%= submit_tag "Submit Edited Question", id: "submit-edit-question-btn",class: "btn btn-success" %>
<%= submit_tag "Preview", class: "btn btn-default" %>
<% end %>
<p></p>
<div id="preview-container">
</div>

app/views/questions/_form.html.erb
<!-- NEW QUESTION FORM -->

<%=form_for @question, remote: true do |f| %>
  <br>
  <%= f.text_field :title, placeholder: "Question Subject" %>
  <br>
  <br>
  <%= f.text_area :content, placeholder: "Ask your question here.", cols: "40", rows: "5" %>
  <br>
  <br>
  <%= submit_tag "Submit New Question", id: "submit-new-question-btn",class: "btn btn-success" %>
<% end %>
<p></p>
<div id="preview-container">
</div>

app/views/questions/_questions_table.html.erb
<table class = "questiontable">
  <tr>
  </tr>
  <% @questions.each do |question| %>
    <tr id = "<%=question.id%>">
      <td ><%=link_to "#{question.title}", question_path(question) %></td>
    </tr>

    <tr id = "<%=question.id%>">
      <td><%=question.content %></td>
    </tr>
  <%end %>
  <footer class ="question-footer apple_pagination"><%= will_paginate @questions, :params => {:controller => 'questions', :action => 'index' } %></footer>
</table>

app/views/questions/create.js.erb
// remove any existing input in the form
$(".content-wrapper #new_question")[0].reset();

// add hidden class to wrapper
$(".content-wrapper #question-form").addClass("hidden");

// Show the "Add a question" link
$(".content-wrapper #ask-question-btn").show();

// Add the new question to the list
$(".content-wrapper .questiontable tr:first" ).after("<%= j (render 'row') %>")

app/views/questions/edit.js.erb
// $('.content-wrapper #edit-question-form').html("<%= j (render 'edit_question_form') %>");




// hide the 'Edit' link
$('.content-wrapper #edit-question-btn').hide();

// show the form (to add a new response)
$('.content-wrapper #edit-question-form').html("<%= j (render 'edit_question_form') %>");

app/views/questions/index.html.erb
<div class = "container" style = "margin-bottom: 30px">
	<h3>Questions</h3>

  <% if current_user %>
    <h3><%=link_to "Ask a Question", new_question_path, class: "btn btn-success", id: "ask-question-btn" %></h3>
  <% end %>


  <div id="question-form" class="hidden">
    <%=render "form" %>
  </div>

  <%=render "questions_table", locals: {questions: @questions}%>

</div>

app/views/questions/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-12 tile-container">
        <div class="thumbnail">
<div>
  <h1 class = "center"><%=@question.title%></h1>
  <br>
  <p class = "left"><%= @question.content %></p>
  <p class = "text-info"><small>Author: <%=@question.user.email%></small></p>
</div>
</div>
</div>


<div class="container">
    <div class="row">
      <div class="col-xs-12 tile-container">
        <div class="thumbnail">
<div class = "answers">
  <% @question.responses.each do |response| %>
  <p class = "left">Response: <%= response.content%></p>
  <% end %>
</div>
</div>
</div>

<div class="container">

    <div class="row">
      <div class="col-xs-12 tile-container">
        <div class="thumbnail">
<%=link_to "Respond", new_question_response_path(question_id: @question.id), remote: true, id: "add-response-btn", class: "btn btn-success" %>
<br>
<br>
<div id = "respond-question-form"></div>

<% if current_user == @question.user%>
  <%=link_to "Edit Question", edit_question_path(question: @question), remote: true, id: "edit-question-btn", class: "btn btn-warning" %>
  <% end %>
  <div id = "edit-question-form"></div>
</div>
</div>
</div>

app/views/questions/update.js.erb
window.location.replace("<%= questions_path %>");