config/routes.rb
Rails.application.routes.draw do

  root to: 'meetups#index'

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users, only: [:show]
  resources :maps, only: [:index]
  match '/auth', :to => 'authorizations#new', :as => :login, :via => [:get, :post]
  match '/auth/:provider/callback', :to => 'authorizations#create', :via => [:get, :post]
  match '/auth/failure', :to => 'authorizations#failure', :via => [:get, :post]

  get 'search', to: 'search#search'

  resources :meetups
  resources :meetup_memberships

  resources :questions do
    resources :responses
  end
  resources :courses
  resources :groups, only: [:index]
  resources :conversations do
    resources :messages
  end

end

app/models/meetup.rb
require 'elasticsearch/model'
class Meetup < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :course
  belongs_to :venue
  belongs_to :organizer, class_name: "User"
  has_many :meetup_memberships, dependent: :destroy
  has_many :users, through: :meetup_memberships
  has_many :course_meetups
  has_many :courses, through: :course_meetups
end

Meetup.import

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  def index
    #upcoming and suggested
    @upcoming = upcoming_meetups
    if current_user
      array_of_titles = []
      user_courses = current_user.courses
      user_courses.each{|course| array_of_titles << course.title}
      clean_query = SearchSanitizer.new(array_of_titles.flatten.join(" "))
      @courses_based_meetups = Meetup.search(query: {match: {_all: {query: clean_query.sanitized, fuzziness: 1}}})

      # OLDER IF ISSUE ASK JD ####################################################################
      # @courses_based_meetups = Meetup.search(query: {multi_match: {_all: {query: clean_query.sanitized, fuzziness: 1, fields: ['title^10', 'body']}}})

      # @courses_based_meetups = Meetup.search(clean_query.sanitized)
      #############################################################################@##############

      # puts clean_query.sanitized

      test = SearchSanitizer.new(current_user.questions.pluck(:title).join(" "))
      puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
      puts clean_query.sanitized
      puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
      @meetups = Meetup.search(test.sanitized)
      @meetups = Meetup.search(query: {match: {_all: {query: test.sanitized, fuzziness: 1}}})
    end
  end

  def new
    @meetup = Meetup.new
    @venues = Venue.all
  end

  def create
    @course = Course.find_by_title(params[:meetup][:course])
    @venue = Venue.find_by_name(params[:meetup][:venue])
    @meetup = Meetup.create(
      course: @course,
      venue: @venue,
      organizer: current_user,
      title: params[:meetup][:title],
      description: params[:meetup][:description],
      scheduled_date: params[:meetup][:scheduled_date],
      begin_time: params[:meetup][:begin_time],
      end_time: params[:meetup][:end_time]
    )
    redirect_to meetup_path(@meetup)

  end

  def show
    # @users = User.all find users in the particular meetup
    @meetup = Meetup.find(params[:id])
    @users = MeetupMembership.where(meetup: @meetup).map{ |e| User.find(e.user_id)}
    @organizer = User.find(@meetup.organizer_id)
    @venue = Venue.find(@meetup.venue_id)
  end

  def upcoming_meetups
   @meetups =[]
   MeetupMembership.where(user: current_user).each do |membership|
      @meetups << Meetup.find(membership.meetup_id)
   end
    @meetups
  end

  # def suggested_meetups
  #   if current_user
  #     test = SearchSanitizer.new(current_user.questions.pluck(:title).join(" "))
  #     @meetups = Meetup.search(query: {multi_match: {_all: {query: test.sanitized, fuzziness: 1, fields: ['title^10', 'body']}}})
  #     binding.pry
  #     p @meetups
  #     p @meetups
  #   end
  # end

  def destroy
    meetup = Meetup.find(params[:id])
    if meetup
      meetup.destroy
      redirect_to meetups_path
    else
      redirect_to meetups_path
    end
  end

  def meetup_params
    #get attributed from db
    params.require(:meetup).permit(:title, :venue)
  end
end

app/views/meetups/index.html.erb
<div class="container">
  <%if not @upcoming.empty? %>
    <div class="row">
      <div class="col-xs-12 tile-container">
        <div class="thumbnail">
          <h1>Your Upcoming Meetups</h1>

          <% @upcoming.each do |meetup| %>

          <%= link_to meetup_path(meetup.id) do %>
            <p><b><%= meetup.title %></b></p>
          <% end %>
            <p><%= meetup.description %></p><br>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <% if not @meetups.first.nil? %>
    <div class="row">
      <div class="col-xs-12 tile-container">
        <div class="thumbnail">
          <h1>Meetups Based on Your Previous Questions</h1>
          <% @meetups.each do |meetup| %>
          <p><b><%= link_to meetup.title, meetup_path(meetup.id) %></b></p>
          <p><%= meetup.description %></p><br>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <% if not @courses_based_meetups.nil? %>
    <div class="row">
      <div class="col-xs-12 tile-container">
        <div class="thumbnail">
          <h1>Meetups Based on Your Courses</h1>
          <% @courses_based_meetups.each do |meetup| %>
            <p><b><%= link_to meetup.title, meetup_path(meetup.id) %></p></b>
          <% end %>
          <%= link_to "Back to Home", meetups_path %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% unless current_user%>
<div class = "container">
<h2>We're glad you're here.</h2><br>
  <p>Learning solo can be difficult. <br>
    In Session is an online community providing students with a way to learn and support each other. <br>Through our website, students can join in-person study sessions, chat with peers and post on forums.</p>

  <p>In Session is a website created by five DevBootcamp students. As constant learners, often online, we recognized the void between students </p>
</div>
<% end %>

app/views/meetups/new.html.erb
<div class = "container">
<h2>Add A New Meetup</h2>
<%= form_for @meetup do |f|  %>

 <div class="field"> 
      <%= f.label :course, "Course Title:" %> <br /> 
      <%= f.select 'course', current_user.courses.map {|course| [ course.title, course.title ] }, { prompt: "Select Course" } %>
</div>
<div class="field"> 
      <%= f.label :name, "Venue: " %> <br /> 
      <%= f.select 'venue', @venues.map {|venue| [ venue.name + " Library", venue.name ] }, { prompt: "Select Venue" } %>
</div>

<div class="field"> 
      <%= f.label :title, "Meetup Name: " %> <br /> 
      <%= f.text_field :title %>
</div>
<div class="field"> 
      <%= f.label :description, "Description: " %> <br /> 
      <%= f.text_area :description %>
</div>
<div class="field"> 
      <%= f.label :scheduled_date, "Meetup Day: " %> <br /> 
      <%= f.date_field :scheduled_date %>
</div>

<div class="field"> 
      <%= f.label :begin_time, "Begin Time: " %> <br /> 
      <%= f.time_field :begin_time %>
</div>
<div class="field"> 
      <%= f.label :end_time, "End Time: " %> <br /> 
      <%= f.time_field :end_time %>

</div> 

<br /> 
    <%= submit_tag "Create New Meetup", id: "submit-new-meetup-btn",class: "btn btn-success" %>
<% end %>
</div>

app/views/meetups/show.html.erb
<div class = "container">

  <%= link_to "Back to Meetups", meetups_path %><br>
  <%= link_to "Back to Home", meetups_path %><br><br>
  <% if Meetup.last == @meetup %>
     <h3> Meetup successfully created!</h3>
  <% end %>
  <div class = "jumbotron">
        <h1><%= @meetup.title %></h1>
        <p>Course: <%= @meetup.course.title %></p><br>
        <p>Description of Meetup: <%= @meetup.description %></p><br>
        <p><b>Start Day: </b><%= @meetup.scheduled_date.strftime("%B %d, %Y") %></p>
        <p><b>Start Time:</b> <%= @meetup.begin_time.strftime(" %H:%M") %></p>
         <p><b>End Time: </b><%= @meetup.end_time.strftime(" %H:%M") %></p>
        <p>Location: <%= link_to @venue.name, "/maps?meetup_id=#{@meetup.id}" %></p>
        <p>Organizer: <%= @organizer.name %></p>
        <div class="meetup-list">
          <% @meetup.users.each_with_index do |user, index| %>
          <div class="row">
            <div class="chat-button col-xs-2" >
              <%= link_to "", "/conversations/1", class: "fa fa-envelope btn btn-success btn-xs start-conversation", "data-sid" => current_user.id, "data-rip" =>   user.id%>
            </div>
            <div class="meetup-member col-xs-9" style="v-align: middle">
              <%= link_to user.name, user_path(user) %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-xs-12 tile-container">
      <div class="thumbnail">

        <% unless current_user.meetups.include?(@meetup) %>
          <%= link_to "Join this Meetup", new_meetup_membership_path(id: @meetup.id), class: "btn btn-success" %>
        <% else %>
          <%= link_to "Leave this Meetup", meetup_membership_path(@meetup.meetup_memberships.find_by(user: current_user)), method: :delete, class: "btn btn-warning"%>
        <% end %>
        <% if current_user == @organizer %>
          <%= link_to "Delete this Meetup", meetup_path(@meetup), method: :delete, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
</div>