config/routes.rb
Rails.application.routes.draw do

  root to: 'meetups#index'

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users, only: [:show]
  resources :maps, only: [:index]
  match '/auth', :to => 'authorizations#new', :as => :login, :via => [:get, :post]
  match '/auth/:provider/callback', :to => 'authorizations#create', :via => [:get, :post]
  match '/auth/failure', :to => 'authorizations#failure', :via => [:get, :post]

  get 'search', to: 'search#search'

  resources :meetups
  resources :meetup_memberships

  resources :questions do
    resources :responses
  end
  resources :courses
  resources :groups, only: [:index]
  resources :conversations do
    resources :messages
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :meetup_memberships
  has_many :meetups, through: :meetup_memberships
  has_many :organized_meetups, class_name: "Meetup", foreign_key: :organizer_id
  has_many :user_exercises
  has_many :exercises, through: :user_exercises
  has_many :course_memberships
  has_many :courses, through: :course_memberships


  has_many :questions
  has_many :responses

  has_many :authorizations
  validates :first_name, :email, :presence => true #lines 2 and 3 are from tutsplus tutorial
  validates :last_name, :email, :presence => true  #lines 2 and 3 are from tutsplus tutorial

  # GEOCODER
  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def add_provider(auth_hash)
    # Check if the provider already exists, so we don't add it twice
    unless authorizations.find_by_oauth_credentials(auth_hash)
      provider = Provider.find_by(name: auth_hash[:provider])
      Authorization.create :user => self, :provider => provider, :uid => auth_hash[:uid], :user_token => auth_hash.credentials[:token], :user_secret => auth_hash.credentials[:secret]
    end
  end

  def oauth_request(auth_hash, url_stub)
    provider = Provider.find_by("name" => auth_hash["provider"])
    oauth_token = auth_hash["extra"].access_token
    consumer = auth_hash["extra"]["access_token"].consumer
    full_url = provider.site + url_stub
    uri = URI(full_url) # This is the url that we want to pull data from
    req = Net::HTTP::Get.new(uri)
    response = Net::HTTP.start(uri.hostname, uri.port) do |http|
      req.oauth!(http, consumer, oauth_token)
      http.request(req)
    end
    # puts response.body
    if response.code == "200"
      response
    else
      puts "Error"
    end
  end

  def self.oauth_request
    secret = "ebHgCUXVBmfmtqpQ"                                   # The user secret from the Credentials
    token = "t6480427084414976"                                   # The user token from the Credentials
    oauth_token = OAuth::Token.new(token, secret)
    #                               Our Site Key        Our Site Secret           Our Site Stub
    consumer = OAuth::Consumer.new("UHze9rM6n5NtNee2", "f9Z24DkmGTyWZx5E", site: "http://www.khanacademy.org/api/v1")
    uri = URI("http://www.khanacademy.org/api/v1/user/playlists") # This is the url that we want to pull data from


    req = Net::HTTP::Get.new(uri)                                 # This is the GET request

    response = Net::HTTP.start(uri.hostname, uri.port) do |http|  # This is processing the request
      req.oauth!(http, consumer, oauth_token)                     # .oauth! call which formats the request
      http.request(req)                                           # The actual http request is made here
    end
    puts response.body                                            # <Net::HTTPOK:0x007f88b30485b0> body content
  end

  #GEOCODER
  def full_street_address
    [street_address, city, state, zip].compact.join(', ')
  end

  def name
    [first_name, last_name].join(' ')
  end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user.id



    @meetups_near_me = Array.new
    @courses = Array.new
    @meetups = Array.new

    @venues_near_me = Venue.near([current_user.latitude, current_user.longitude], current_user.max_distance)

    @venues_near_me.each do |venue|
      @meetups_near_me << venue.meetups if venue.meetups.length > 0
    end

    @meetups_near_me.flatten!

    @meetups_near_me.each do |meetup|
      @courses << [meetup.course.title, meetup.id]
    end
    render :show
  end

  def edit
    @user = current_user
  end

  def update
  end

end

app/views/users/edit.html.erb
<!-- Link your Khan Academy Account -->
  <div class="container">

    <div class="row">
      <div class="col-xs-12 tile-container">
        <div class="thumbnail">
          <%= link_to image_tag("sarah.jpg", :class => "img-circle") %>
          <div class="caption">
            <li><%= @current_user.first_name.capitalize + " " + @current_user.last_name.capitalize %></li>
            <li><%= @current_user.email %></li>
            <li><%= @current_user.preferred_language = "Preferred Language: Spanish" %></li>
          </div>
          <i class="fa fa-leaf"></i>
<!--           <i class="fa fa-jsfiddle"></i> -->
        </div>
      </div>
    </div>

<!-- CURRENT COURSES -->

  <div class="row">
    <div class="col-xs-12 tile-container">
      <div class="thumbnail">
        <h3>Current Courses</h3>
        <% if @current_user.meetups %>
        <% @current_user.meetups.each do |meetup| %>
        <li><%= link_to meetup.course.title, '#' %></li>
        <% end %>
        <% else %>
        <p>You are not currently enrolled in any courses"</p>
        <% end %>
      </div>
      <div class="completed_courses_container">        
        <h4 class="completed_courses_header">Completed Courses</h4>
        <div class="chevron_completed">
          <a href="#"><i class="fa fa-chevron-down"></i></a>
        </div>
      </div>
    </div>
  </div>




<!-- MEETUPS NEARBY -->

  <div class="row">
    <div class="col-xs-12 tile-container">
      <div class="thumbnail">
        <h3>Meetups Nearby</h3>
        <ul class="meetups_nearby">
          <div class="visible_meetups_nearby">
            <% @courses[0...4].each do |course| %>
              <li><%= link_to course, maps_path %></li>
            <% end %>
          </div>
          <div class="hidden_meetups_nearby">
            <% @courses[5...@courses.length].each do |course| %>
              <li><%= link_to course, maps_path %></li>
            <% end %>
          </div>
        </ul>
      </div>
      <div class="meetups_nearby_container">
        <h4 class="meetups_nearby_header">More</h4>
        <div class="chevron_nearby">
          <a href="#"><i class="fa fa-chevron-down"></i></a>
        </div>
      </div>
    </div>
  </div>

<!-- BIO -->

  <div class="row">
    <div class="col-xs-12 tile-container">
      <div class="thumbnail">
        <h3>Bio</h3>
        <p><%= @current_user.bio %></p>
      </div>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<!-- Link your Khan Academy Account -->
  <div class="container">

    <div class="row">
      <div class="col-xs-12 tile-container">
        <div class="thumbnail">
          <%= link_to image_tag("sarah.jpg", :class => "img-circle") %>
          <div class="caption">
            <li><%= @current_user.first_name.capitalize + " " + @current_user.last_name.capitalize %></li>
            <li><%= @current_user.email %></li>
            <li>Preferred Language: <%= @current_user.preferred_language %></li>
            <h3><%= link_to "Add a Course", new_course_path, class: "btn btn-success" %></h3>
          </div>
        </div>
      </div>
    </div>

<!-- CURRENT COURSES -->
<% if @current_user.meetups %>
  <div class="row">
    <div class="col-xs-12 tile-container">
      <div class="thumbnail">
        <h3>Current Meetups</h3>
        <% @current_user.meetups.each do |meetup| %>
        <li><%= link_to meetup.course.title, meetup_path(meetup) %></li>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<!-- MEETUPS NEARBY -->

<div class="row">
  <div class="col-xs-12 tile-container">
    <div class="thumbnail">
      <h3><%= link_to "Create a Meetup", new_meetup_path, class: "btn btn-success" %></h3>
      <h3>Meetups Nearby</h3>
      <ul class="meetups_nearby">
        <div class="visible_meetups_nearby">
          <% @courses[0...4].each do |course| %>
            <li><%= link_to course[0], meetup_path(course[1]) %></li>
          <% end %>
        </div>
        <div class="hidden_meetups_nearby">
          <% @courses[5...@courses.length].each do |course| %>
            <li><%= link_to course[0], meetup_path(course[1]) %></li>
          <% end %>
        </div>
      </ul>
    </div>
    <div class="meetups_nearby_container">
      <h4 class="meetups_nearby_header">More</h4>
      <div class="chevron_nearby">
        <a href="#"><i class="fa fa-chevron-down nearby"></i></a>
      </div>
    </div>
  </div>
</div>

<!-- BIO -->

  <div class="row">
    <div class="col-xs-12 tile-container">
      <div class="thumbnail">
        <h3>Bio</h3>
        <p class="bio"><%= @current_user.bio %></p>
      </div>
    </div>
  </div>

</div>